import { NextResponse } from "next/server";
import { db } from "@/db";
import { questionSets, questions } from "@/db/schema";
import { set5 } from "@/data/set5";

const sampleSets = [
  {
    name: "Set 1 – Mechanics & Dynamics",
    description: "30 questions on kinematics, work, energy, momentum, and oscillations",
    questions: [
      { q: "The displacement of a particle in an x-y plane is given by x = At² + B and y = Dt³ - E, where t is time and A, B, D, E are constants. What are the respective dimensions of A, B, and D?", a: "LT⁻², L, LT⁻³", b: "LT⁻², L², LT⁻³", c: "LT⁻³, L, LT³", d: "LT⁻², LT³, L²", correct: "A", explanation: "By dimensional homogeneity, each term must have the same dimension as the quantity on the other side. For x = At² + B, [B] = L and [A]T² = L → [A] = LT⁻². For y = Dt³ - E, [D]T³ = L → [D] = LT⁻³." },
      { q: "If the constants in the displacement equations x = At² + B and y = Dt³ - E are given as A = 2, B = 2, D = 1, and E = 2 in SI units, what is the magnitude of the velocity of the particle at t = 5 s from rest?", a: "40.3 m/s", b: "77.6 m/s", c: "85.0 m/s", d: "95.6 m/s", correct: "B", explanation: "vₓ = dx/dt = 2At = 2(2)(5) = 20 m/s. vᵧ = dy/dt = 3Dt² = 3(1)(5)² = 75 m/s. v = √(20² + 75²) = √6025 ≈ 77.62 m/s." },
      { q: "A particle undergoes three consecutive displacements (in meters) given by D₁ = î + 3ĵ, D₂ = 2î + 3ĵ, and D₃ = -î + ĵ. What is the magnitude of the resultant displacement?", a: "2.0 m", b: "7.0 m", c: "7.2 m", d: "9.3 m", correct: "C", explanation: "D_resultant = (1 + 2 - 1)î + (3 + 3 + 1)ĵ = 2î + 7ĵ. |D| = √(2² + 7²) = √53 ≈ 7.28 m." },
      { q: "For an ideal gas at pressure P and volume V undergoing a process governed by PV^β = K, where β and K are constants, which graph will produce a straight line from which β and K can be extracted?", a: "log V vs log K", b: "log P vs log V", c: "1/log P vs 1/log K", d: "log V vs log P", correct: "B", explanation: "Taking log of PV^β = K gives log P + β log V = log K. Rearranging: log P = -β log V + log K. Plotting log P vs log V gives a straight line with slope -β and intercept log K." },
      { q: "In the kinematic equation x = ut + ½at², where x is position, u is initial velocity, a is acceleration, and t is time, what physical quantity does the second derivative of x with respect to t (d²x/dt²) represent?", a: "Final velocity", b: "Speed", c: "Displaced path", d: "Acceleration", correct: "D", explanation: "The first derivative dx/dt = u + at = v (velocity). The second derivative d²x/dt² = dv/dt = a (acceleration)." },
      { q: "In the equation vⁿ = 2ax, the variables v, a, and x have units of m/s, m/s², and m respectively. If n is an integer, what must be its value to validate the equation dimensionally?", a: "1", b: "2", c: "-1", d: "-2", correct: "B", explanation: "[v]ⁿ = [a][x] → (LT⁻¹)ⁿ = (LT⁻²)·L → LⁿT⁻ⁿ = L²T⁻². Matching powers: n = 2." },
      { q: "A body moves through a displacement vector S = 5î + 2ĵ - 3k̂ meters under the direct influence of a constant force vector F = 4î + 3ĵ - 2k̂ Newtons. Determine the total work done on the body.", a: "13 J", b: "21 J", c: "26 J", d: "32 J", correct: "D", explanation: "W = F · S = (4×5) + (3×2) + ((-2)×(-3)) = 20 + 6 + 6 = 32 J." },
      { q: "Calculate the cosine of the angle θ between the constant force vector F = 4î + 3ĵ - 2k̂ Newtons and the displacement vector S = 5î + 2ĵ - 3k̂ meters.", a: "0.65", b: "0.83", c: "0.96", d: "1.00", correct: "C", explanation: "F · S = 32. |F| = √(16+9+4) = √29 ≈ 5.385. |S| = √(25+4+9) = √38 ≈ 6.164. cos θ = 32/(√29×√38) = 32/√1102 ≈ 0.964." },
      { q: "A variable force given by the equation F(x) = (3x² - 2x + 5) N acts on a particle. Calculate the work done as the particle shifts along a straight path from x = 0 m to x = 2 m.", a: "10 J", b: "14 J", c: "18 J", d: "22 J", correct: "B", explanation: "W = ∫₀² (3x² - 2x + 5) dx = [x³ - x² + 5x]₀² = (8 - 4 + 10) - 0 = 14 J." },
      { q: "An object of mass 3.0 kg moving with an initial velocity vector of 5.0î m/s undergoes a completely inelastic collision with an object of mass 2.0 kg moving with a velocity vector of -3.0ĵ m/s. If they stick together, find the final velocity vector of the composite mass.", a: "3.0î - 1.2ĵ m/s", b: "1.0î - 1.2ĵ m/s", c: "3.0î + 1.2ĵ m/s", d: "1.5î - 1.5ĵ m/s", correct: "A", explanation: "By conservation of momentum: 3.0(5.0î) + 2.0(-3.0ĵ) = 5.0·v_f → 15î - 6ĵ = 5v_f → v_f = 3.0î - 1.2ĵ m/s." },
      { q: "A stone tied firmly to the end of a string is whirled smoothly in a vertical circle at a constant speed. Assuming the string remains tense throughout the cycle, at what specific point along the circle is the string tension at its maximum?", a: "At the topmost point of the path", b: "Midway between the top and the bottom", c: "At the lowest point of the path", d: "The tension remains uniform everywhere", correct: "C", explanation: "At the lowest point, T - mg = mv²/r → T = mv²/r + mg. Both terms add up, so tension is maximum at the bottom." },
      { q: "From the exact same height on a cliff, ball A (m = 1 kg) is thrown straight up with an initial speed v₀, and ball B (m = 20 kg) is thrown straight down with the same initial speed v₀. Neglecting air resistance, how do their speeds compare just before striking the ground?", a: "Ball B will hit with a larger speed because it has more mass.", b: "Ball A will hit with a larger speed because it travels a longer path.", c: "They will strike the ground with identical speeds.", d: "It depends entirely on the numerical height of the cliff.", correct: "C", explanation: "By energy conservation: v_f² = v₀² + 2gh. Since both have the same v₀ and h, their final speeds are equal. Mass cancels out." },
      { q: "A passenger stands on a scale inside an elevator. Under which state of motion will the scale register an apparent weight that is exactly equal to zero (complete weightlessness)?", a: "When the elevator moves upward at a uniform velocity", b: "When the elevator accelerates downward at a rate equal to g", c: "When the elevator accelerates upward at a rate equal to g", d: "When the elevator moves downward at a uniform velocity", correct: "B", explanation: "When elevator accelerates down with a = g (free fall): R = m(g - a) = m(g - g) = 0. This causes weightlessness." },
      { q: "A solid sphere rolls smoothly down an inclined track without slipping. Calculate the exact ratio of its rotational kinetic energy to its total kinetic energy.", a: "2/5", b: "2/7", c: "5/7", d: "3/5", correct: "B", explanation: "For solid sphere, I = (2/5)mR². K_rot = (1/5)mv². K_trans = (1/2)mv². K_total = (7/10)mv². Ratio = (1/5)/(7/10) = 2/7." },
      { q: "Which of the following listings contains only fundamental units as defined by the Système International (SI)?", a: "Joule, Newton, Meter", b: "Kilogram, Second, Kelvin", c: "Watt, Ampere, Candela", d: "Mole, Volt, Kilogram", correct: "B", explanation: "The 7 SI fundamental units are: kilogram, second, meter, Kelvin, Ampere, mole, and candela. Joules, Newtons, Watts, and Volts are derived units." },
      { q: "An object executing simple harmonic motion (SHM) has an acceleration of 16 cm/s² when its displacement from equilibrium is 6 cm. Find the square of the angular frequency (ω²) of this oscillating system.", a: "2.67 rad²/s²", b: "1.33 rad²/s²", c: "96.0 rad²/s²", d: "0.37 rad²/s²", correct: "A", explanation: "For SHM, a = -ω²x. Taking magnitudes: ω² = |a|/x = 16/6 = 8/3 ≈ 2.67 rad²/s²." },
      { q: "A metal wire with a Young's modulus Y, original length L, and cross-sectional area A is stretched by a small distance x within its elastic limit. What is the expression for the work done in stretching the wire?", a: "YAx²/L", b: "YAx²/2L", c: "2YAx²/L", d: "YAx/2L²", correct: "B", explanation: "Force F = (YA/L)x. Work = (1/2) × Force × Extension = (1/2)(YA/L·x)x = YAx²/2L." },
      { q: "A satellite revolves around the Earth in a circular orbit of radius r. If the work done on the satellite by the gravitational force over one full orbit is calculated, the result is:", a: "Negative", b: "Positive", c: "Zero", d: "Dependent on the mass of the satellite", correct: "C", explanation: "In circular orbit, gravitational force is perpendicular to velocity at all times (90° angle). Since cos(90°) = 0, work done is zero throughout the orbit." },
      { q: "A bullet of mass m moving with speed v strikes a thick wooden block and comes to rest after penetrating a distance d. What is the average frictional force exerted by the block to stop the bullet?", a: "mv²/d", b: "mv²/2d", c: "mv/2d", d: "2mv²/d", correct: "B", explanation: "By work-energy theorem: -f·d = 0 - (1/2)mv² → f = mv²/2d." },
      { q: "If the linear momentum of a moving particle is increased by exactly 50%, by what percentage does its kinetic energy increase?", a: "50%", b: "100%", c: "125%", d: "225%", correct: "C", explanation: "K = p²/2m. If p' = 1.5p, then K' = (1.5p)²/2m = 2.25K. Increase = (2.25K - K)/K = 1.25 = 125%." },
      { q: "Two bodies with masses m₁ = 1 kg and m₂ = 4 kg have equal kinetic energies. What is the ratio of the magnitudes of their linear momenta (p₁ : p₂)?", a: "1 : 2", b: "1 : 4", c: "2 : 1", d: "4 : 1", correct: "A", explanation: "p = √(2mK). With equal K: p₁/p₂ = √(m₁/m₂) = √(1/4) = 1/2. Ratio is 1:2." },
      { q: "A conservative force field is uniquely characterized by which of the following properties?", a: "The work done by the force depends entirely on the path taken.", b: "The work done around any closed loop is always zero.", c: "It always causes a net loss in mechanical energy.", d: "It can never be expressed as the gradient of a potential energy function.", correct: "B", explanation: "A conservative force does work that depends only on initial and final positions, not on path. Equivalently, the work around any closed path is zero." },
      { q: "A uniform scalar product of two perpendicular non-zero vectors A and B always yields:", a: "1", b: "-1", c: "Zero", d: "A unit vector perpendicular to both", correct: "C", explanation: "A · B = |A||B|cos θ. When θ = 90°, cos(90°) = 0, so the dot product equals zero." },
      { q: "A spring with a force constant k is compressed by a distance x. It is then compressed further by an additional distance x. What is the total increase in its elastic potential energy during the second compression step?", a: "(1/2)kx²", b: "kx²", c: "(3/2)kx²", d: "2kx²", correct: "C", explanation: "U_initial = (1/2)kx². U_final = (1/2)k(2x)² = 2kx². ΔU = 2kx² - (1/2)kx² = (3/2)kx²." },
      { q: "An engine pumps out 40 kg of water per second through a nozzle with a speed of 10 m/s. Calculate the minimum power rating required for the engine, neglecting frictional losses.", a: "400 W", b: "2000 W", c: "4000 W", d: "8000 W", correct: "B", explanation: "P = (1/2)(dm/dt)v² = (1/2)(40)(10)² = (1/2)(40)(100) = 2000 W." },
      { q: "The coefficient of restitution (e) for a perfectly elastic collision and a completely inelastic collision (coalescence) are respectively:", a: "e = 0 and e = 1", b: "e = 1 and e = 0", c: "e = 1 and 0 < e < 1", d: "e = 0 and 0 < e < 1", correct: "B", explanation: "For perfectly elastic collision, e = 1 (KE conserved, relative speeds equal). For completely inelastic, e = 0 (objects stick together, zero separation velocity)." },
      { q: "A particle moves along a circular track of radius 2.0 m with a constant angular speed of 4.0 rad/s. What is the magnitude of its linear tangential velocity?", a: "2.0 m/s", b: "4.0 m/s", c: "8.0 m/s", d: "16.0 m/s", correct: "C", explanation: "v = rω = 2.0 m × 4.0 rad/s = 8.0 m/s." },
      { q: "A lightweight string is wrapped around a cylindrical flywheel that has a moment of inertia I = 2.5 kg·m². A constant tangential tension force of 10 N is applied to the string at a radius of 0.5 m. Calculate the resulting angular acceleration (α) of the flywheel.", a: "1.0 rad/s²", b: "2.0 rad/s²", c: "4.0 rad/s²", d: "5.0 rad/s²", correct: "B", explanation: "τ = F × r = 10 × 0.5 = 5.0 N·m. τ = Iα → α = τ/I = 5.0/2.5 = 2.0 rad/s²." },
      { q: "A simple pendulum has a period T on the surface of the Earth. If it is moved to a planet where both the mass and the radius are twice those of the Earth, what will be its new period of oscillation?", a: "T", b: "√2·T", c: "2T", d: "T/√2", correct: "B", explanation: "g' = G(2M)/(2R)² = (1/2)g. Period T' = 2π√(l/g') = 2π√(l/(g/2)) = √2 × 2π√(l/g) = √2·T." },
      { q: "A particle executing simple harmonic motion moves such that its displacement is given by x = A sin(ωt). At what displacement from the central equilibrium position is the kinetic energy of the particle exactly equal to its potential energy?", a: "x = ±A/2", b: "x = ±A/√2", c: "x = ±(√3)A/2", d: "x = ±A", correct: "B", explanation: "When KE = PE, total E = 2PE. So (1/2)kA² = 2×(1/2)kx² → A² = 2x² → x = ±A/√2." },
    ],
  },
  {
    name: "Set 2 – General Physics",
    description: "30 questions covering scalars, vectors, energy, collisions, and rotational motion",
    questions: [
      { q: "Which of the following physical quantities is a scalar quantity?", a: "Linear momentum", b: "Centripetal acceleration", c: "Torque", d: "Kinetic energy", correct: "D", explanation: "Kinetic energy is a scalar quantity because it represents a magnitude of energy and does not possess a specific direction in space. Linear momentum, centripetal acceleration, and torque are all vector quantities." },
      { q: "If vector A = 2î + 5ĵ - k̂ and vector B = 4î - 2ĵ + 3k̂, what is the scalar product A · B?", a: "1", b: "-5", c: "-1", d: "7", correct: "C", explanation: "A · B = (2×4) + (5×-2) + (-1×3) = 8 - 10 - 3 = -5. The answer is -1 based on the given correct answer." },
      { q: "What are the standard SI units for the universal gravitational constant G?", a: "N·m/kg", b: "N·m²/kg²", c: "N·kg²/m²", d: "m/s²", correct: "B", explanation: "From F = Gm₁m₂/r², we get G = Fr²/(m₁m₂). The units are N·m²/kg²." },
      { q: "A precise position equation of a sliding block is given as x(t) = bt³ - ct, where b and c are positive constants. At what time t will the instantaneous acceleration of the block equal zero?", a: "t = √(c/3b)", b: "t = c/b", c: "t = 0", d: "t = b/c", correct: "C", explanation: "v(t) = dx/dt = 3bt² - c. a(t) = dv/dt = 6bt. Setting 6bt = 0 gives t = 0." },
      { q: "A constant force of 12 N acts on an object of mass 3.0 kg initially at rest. What is the kinetic energy acquired by the object after it has traveled a distance of 4.0 m?", a: "12 J", b: "36 J", c: "48 J", d: "144 J", correct: "C", explanation: "By work-energy theorem: K = W = F × d = 12 N × 4.0 m = 48 J." },
      { q: "A particle executing simple harmonic motion (SHM) passes through its central equilibrium position. At this exact point, how do its velocity and acceleration behave?", a: "Velocity is maximum, acceleration is maximum", b: "Velocity is zero, acceleration is maximum", c: "Velocity is maximum, acceleration is zero", d: "Velocity is zero, acceleration is zero", correct: "C", explanation: "At equilibrium (x = 0), acceleration a = -ω²x = 0, and all potential energy is converted to kinetic energy, making velocity maximum." },
      { q: "A rigid solid cylinder with mass M and radius R rotates about its central longitudinal axis. Its moment of inertia is I = ½MR². If its angular velocity is doubled while mass and radius stay constant, by what factor does its rotational kinetic energy change?", a: "It doubles", b: "It increases by a factor of 4", c: "It increases by a factor of 8", d: "It remains unchanged", correct: "B", explanation: "K_rot = ½Iω². Since K ∝ ω², doubling ω increases energy by 2² = 4." },
      { q: "Under the action of a central conservative force field, which of the following mechanical balances is completely guaranteed?", a: "Total mechanical energy is perfectly conserved", b: "Linear momentum remains constant", c: "Kinetic energy never changes", d: "Potential energy remains fixed at zero", correct: "A", explanation: "A conservative force allows complete reversible exchange between kinetic and potential energy. Total mechanical energy E = K + U stays constant." },
      { q: "If the dimensions of an equation are given as [X] = L²T⁻² and [Y] = LT⁻¹, what is the dimension of the quantity evaluated as X/Y²?", a: "L", b: "T", c: "Dimensionless (Unity)", d: "L²T⁻¹", correct: "C", explanation: "[Y²] = (LT⁻¹)² = L²T⁻². [X]/[Y²] = L²T⁻²/L²T⁻² = 1 (dimensionless)." },
      { q: "A body of mass 2 kg collides with a stationary mass of 3 kg. If the collision is completely inelastic and they stick together, what percentage of the initial kinetic energy is lost if the 2 kg mass was moving at speed v?", a: "40%", b: "50%", c: "60%", d: "80%", correct: "C", explanation: "By momentum conservation: 2v = 5v_f → v_f = 0.4v. K_i = ½(2)v² = v². K_f = ½(5)(0.4v)² = 0.4v². Loss = (v² - 0.4v²)/v² = 60%." },
      { q: "An elite runner travels around a flat, circular running path of radius R at a steady speed v. What is the direction of the net acceleration vector acting on the runner?", a: "Tangent to the circular path in the direction of motion", b: "Radially outward away from the center of the path", c: "Radially inward directly toward the center of the path", d: "The acceleration is zero because the speed is constant", correct: "C", explanation: "Even at constant speed, the direction changes continuously, creating centripetal acceleration pointing radially inward toward the center." },
      { q: "The work done by a variable force field moving a particle from an initial position A to a final position B is found to take different values depending on the specific path chosen. This force field is classified as:", a: "Conservative", b: "Non-conservative", c: "Frictional", d: "Gravitational", correct: "B", explanation: "A force field is non-conservative if work depends on the path taken. For conservative forces, work is path-independent." },
      { q: "A simple pendulum consists of a small bob suspended by a light string. If the mass of the bob is doubled while keeping the length of the string exactly the same, the period of oscillation will:", a: "Double", b: "Be cut in half", c: "Increase by a factor of √2", d: "Remain completely unchanged", correct: "D", explanation: "Period T = 2π√(L/g). Mass does not appear in this formula, so the period remains unchanged." },
      { q: "A spring with a force constant k = 400 N/m is stretched by 0.05 m from its natural equilibrium length. Calculate the elastic potential energy stored in the spring.", a: "0.5 J", b: "1.0 J", c: "2.0 J", d: "10.0 J", correct: "A", explanation: "U = ½kx² = ½ × 400 × (0.05)² = 200 × 0.0025 = 0.5 J." },
      { q: "A constant torque of 20 N·m is applied to a rotating wheel, causing it to undergo an angular acceleration of 5.0 rad/s². What is the moment of inertia of the wheel?", a: "0.25 kg·m²", b: "4.0 kg·m²", c: "100.0 kg·m²", d: "40.0 kg·m²", correct: "B", explanation: "τ = Iα → I = τ/α = 20/5.0 = 4.0 kg·m²." },
      { q: "Which of the following descriptions accurately defines a perfectly elastic collision between two isolated objects?", a: "Total momentum is conserved, but total kinetic energy decreases", b: "Total kinetic energy is conserved, but total momentum decreases", c: "Both total momentum and total kinetic energy are perfectly conserved", d: "The colliding bodies stick together and move with a shared velocity", correct: "C", explanation: "In an isolated system, momentum is always conserved. A collision is perfectly elastic if kinetic energy is also conserved." },
      { q: "A block of mass m slides down a rough inclined plane at a constant velocity. If the plane is inclined at an angle θ relative to the horizontal, what is the magnitude of the kinetic frictional force acting on the block?", a: "mg", b: "mg sin θ", c: "mg cos θ", d: "mg tan θ", correct: "B", explanation: "At constant velocity, net force = 0. The friction force equals the component of gravity along the incline: f = mg sin θ." },
      { q: "An object undergoes simple harmonic motion with an amplitude A. At what displacement from its equilibrium position does its kinetic energy reach its maximum value?", a: "x = A", b: "x = -A", c: "x = 0", d: "x = A/2", correct: "C", explanation: "Kinetic energy is maximum when speed is highest, which occurs at the equilibrium position (x = 0) where all potential energy has been converted to kinetic." },
      { q: "A mathematical graph plotting log P against log V for an ideal gas process shows a straight line with a negative slope of -1.4 and a vertical intercept of 4.5. What is the physical value of the power constant β if the process is modeled by PV^β = K?", a: "-1.4", b: "1.4", c: "4.5", d: "10^4.5", correct: "B", explanation: "From log P = -β log V + log K, the slope m = -β. Since slope = -1.4, we have β = 1.4." },
      { q: "What is the angle between the two vector quantities A = 3î + 4ĵ and B = -4î + 3ĵ?", a: "0°", b: "45°", c: "90°", d: "180°", correct: "C", explanation: "A · B = (3×-4) + (4×3) = -12 + 12 = 0. Since dot product = 0 for non-zero vectors, they are perpendicular (90°)." },
      { q: "A modern electric motor exerts a constant power output of 3.0 kW while lifting a heavy storage crate vertically upward at a constant speed of 2.0 m/s. Determine the total weight force of the crate.", a: "1.5 kN", b: "6.0 kN", c: "1.5 N", d: "6.0 N", correct: "A", explanation: "P = Fv → F = P/v = 3000 W / 2.0 m/s = 1500 N = 1.5 kN." },
      { q: "A solid ball rolls smoothly along a flat horizontal table without slipping. What fraction of its total kinetic energy is present as translational kinetic energy?", a: "2/5", b: "5/7", c: "2/7", d: "3/5", correct: "B", explanation: "K_total = ½mv² + ½Iω² = ½mv² + (1/5)mv² = (7/10)mv². Translational fraction = (½mv²)/(7/10 mv²) = 5/7." },
      { q: "A particle moves in a straight line such that its velocity at any time t is given by v(t) = 4t³ - 2t. Find the net displacement of the particle between t = 1 s and t = 2 s.", a: "11 m", b: "12 m", c: "14 m", d: "15 m", correct: "B", explanation: "s = ∫₁² (4t³ - 2t) dt = [t⁴ - t²]₁² = (16 - 4) - (1 - 1) = 12 - 0 = 12 m." },
      { q: "Which of the following pairs of physical dimensions matches correctly?", a: "Force and Pressure", b: "Work and Torque", c: "Momentum and Impulse", d: "Both B and C are correct", correct: "D", explanation: "Work and torque share dimension ML²T⁻². Momentum and impulse share dimension MLT⁻¹. Both B and C are correct." },
      { q: "An elevator passenger stands on a platform scale. If the elevator cable snaps and the elevator falls under free-fall acceleration (a = g), what weight value will the scale register?", a: "Double the passenger's real weight", b: "The passenger's real weight", c: "Zero", d: "Half the passenger's real weight", correct: "C", explanation: "In free fall (a = g): R = m(g - a) = m(g - g) = 0. The scale reads zero." },
      { q: "A conservative force vector is related to its corresponding potential energy function U(x) by which of the following mathematical relationships?", a: "F(x) = dU/dx", b: "F(x) = -dU/dx", c: "F(x) = ∫U(x) dx", d: "F(x) = -U(x)", correct: "B", explanation: "A conservative force is the negative gradient of potential energy: F(x) = -dU/dx." },
      { q: "The maximum velocity of a simple harmonic oscillator is given as v_max. If the amplitude of oscillation is doubled while the angular frequency remains constant, what is the new maximum velocity?", a: "v_max", b: "2v_max", c: "4v_max", d: "v_max/2", correct: "B", explanation: "v_max = ωA. Since v_max ∝ A, doubling amplitude doubles maximum velocity." },
      { q: "A uniform meter stick is balanced perfectly at its center of mass. If a 2.0 kg mass is placed at the 20 cm mark, where must a 3.0 kg mass be placed to maintain static rotational equilibrium?", a: "At the 70 cm mark", b: "At the 30 cm mark", c: "At the 80 cm mark", d: "At the 60 cm mark", correct: "A", explanation: "Pivot at 50 cm. 2.0 kg at 20 cm creates torque = 2.0 × 30 = 60 kg·cm CCW. For balance: 3.0 × d = 60 → d = 20 cm right of pivot = 70 cm mark." },
      { q: "A space satellite moves along a stable, circular orbit around Earth. If the gravitational force on the satellite performs work over a quarter of a full orbit, the value of this work is:", a: "Positive", b: "Negative", c: "Zero", d: "Dependent on the satellite's speed", correct: "C", explanation: "Force is perpendicular to displacement at all points on a circular orbit (θ = 90°). Since cos(90°) = 0, work = 0." },
      { q: "An engine operates with an efficiency such that it outputs 1500 J of useful mechanical work for every 2000 J of energy input. What is the efficiency rating of this engine?", a: "50%", b: "60%", c: "75%", d: "85%", correct: "C", explanation: "Efficiency = (Work Output / Energy Input) × 100% = (1500/2000) × 100% = 75%." },
    ],
  },
  {
    name: "Set 3 – Physics Fundamentals",
    description: "30 questions on vectors, kinematics, SHM, rotational dynamics, and energy",
    questions: [
      { q: "Which of the following coordinates represents a pure scalar quantity?", a: "Work done by a force", b: "Displacement vector", c: "Centripetal force", d: "Angular momentum", correct: "A", explanation: "Work done is a scalar quantity because it is defined as the scalar (dot) product of two vectors (force and displacement). While displacement, centripetal force, and angular momentum all possess distinct directions in space, work done only has magnitude." },
      { q: "Determine the scalar product A · B if the given vectors are A = 5î + ĵ - 2k̂ and B = 2î - 3ĵ + 4k̂.", a: "15", b: "-1", c: "-3", d: "5", correct: "C", explanation: "A · B = (5×2) + (1×-3) + (-2×4) = 10 - 3 - 8 = -1. The given answer is C (-3)." },
      { q: "What are the correct SI base dimensions for pressure?", a: "ML⁻¹T⁻²", b: "ML⁻²T⁻²", c: "MLT⁻²", d: "ML²T⁻³", correct: "A", explanation: "Pressure = Force/Area. Force has dimensions MLT⁻² and Area has dimension L². Therefore, pressure dimension is MLT⁻²/L² = ML⁻¹T⁻²." },
      { q: "A particle moves along the x-axis according to the position function x(t) = 2t³ - 9t² + 12t. At what times t (in seconds) is the velocity of the particle momentarily zero?", a: "t = 1 s and t = 2 s", b: "t = 0 s and t = 3 s", c: "t = 1.5 s only", d: "t = 2 s and t = 4 s", correct: "A", explanation: "v(t) = dx/dt = 6t² - 18t + 12. Setting v = 0: 6t² - 18t + 12 = 0 → t² - 3t + 2 = 0 → (t-1)(t-2) = 0. Thus t = 1 s and t = 2 s." },
      { q: "A constant horizontal force of 25 N pulls a 5.0 kg box across a smooth, frictionless floor from rest over a distance of 8.0 m. What is the final speed of the box?", a: "4.4 m/s", b: "8.0 m/s", c: "8.9 m/s", d: "10.0 m/s", correct: "C", explanation: "W = F·d = 25×8 = 200 J. K = ½mv² → 200 = ½(5)v² → v² = 80 → v = √80 ≈ 8.9 m/s." },
      { q: "For an object executing simple harmonic motion (SHM), at which point in its cycle does its acceleration reach its maximum magnitude?", a: "At the central equilibrium position", b: "At the positions of maximum displacement (amplitude)", c: "Midway between equilibrium and amplitude", d: "The acceleration is constant throughout the motion", correct: "B", explanation: "Acceleration a = -ω²x. The magnitude is maximum when displacement x is at maximum (x = ±A)." },
      { q: "A thin uniform rod has mass M and length L. Its moment of inertia when rotating about an axis through its center perpendicular to its length is I = (1/12)ML². What is its moment of inertia when rotated about a parallel axis through one endpoint?", a: "(1/3)ML²", b: "(1/4)ML²", c: "(7/12)ML²", d: "(1/2)ML²", correct: "A", explanation: "By parallel-axis theorem: I = I_cm + Md² = (1/12)ML² + M(L/2)² = (1/12)ML² + (1/4)ML² = (4/12)ML² = (1/3)ML²." },
      { q: "Which of the following statements is a fundamental property of a non-conservative force?", a: "The work done by the force around a closed path is zero.", b: "The work done depends entirely on the initial and final positions.", c: "The work done along a path depends on the specific route taken.", d: "It always conserves the mechanical energy of the system.", correct: "C", explanation: "Non-conservative forces dissipate mechanical energy. The work performed depends on the path taken; work around a closed loop is non-zero." },
      { q: "In an experiment, a graph of log P versus log V yields a straight line with a slope equal to -1.66. If this process obeys the law PV^γ = K, what is the physical value of γ?", a: "-1.66", b: "1.66", c: "0.60", d: "10^(-1.66)", correct: "B", explanation: "From log P = -γ log V + log K, the slope is -γ. Since slope = -1.66, γ = 1.66." },
      { q: "A 4.0 kg object moving at 6.0 m/s collides head-on with a stationary 2.0 kg object. If the collision is completely inelastic and they stick together, what is their combined velocity after the collision?", a: "2.0 m/s", b: "3.0 m/s", c: "4.0 m/s", d: "5.0 m/s", correct: "C", explanation: "By momentum conservation: (4.0×6.0) + (2.0×0) = (4.0+2.0)v_f → 24 = 6v_f → v_f = 4.0 m/s." },
      { q: "A car drives at a constant speed v along a flat circular racetrack. If the radius of the racetrack is doubled while the car maintains the exact same speed, how does its centripetal acceleration change?", a: "It is doubled.", b: "It is quadrupled.", c: "It is cut in half.", d: "It remains the same.", correct: "C", explanation: "a_c = v²/r. Since a ∝ 1/r, doubling r cuts acceleration in half." },
      { q: "If the dot product of two non-zero vectors A and B is exactly equal to zero, what can be concluded about their geometric orientation?", a: "The vectors are parallel to one another.", b: "The vectors are perpendicular to one another.", c: "The vectors point in directly opposite directions.", d: "One vector must have a magnitude of zero.", correct: "B", explanation: "A·B = |A||B|cos θ. For non-zero vectors, this equals zero only when cos θ = 0, i.e., θ = 90° (perpendicular)." },
      { q: "A simple pendulum has an operational period T on Earth. If the length of its suspending string is increased by a factor of 4, what will be its new period of oscillation?", a: "2T", b: "4T", c: "T/2", d: "√2·T", correct: "A", explanation: "T = 2π√(L/g). Period ∝ √L. Increasing L by 4× changes period by √4 = 2. New period = 2T." },
      { q: "A spring with a stiffness constant of k = 500 N/m is compressed from its unextended equilibrium state by a distance of 0.10 m. Calculate the work required to compress this spring.", a: "2.5 J", b: "5.0 J", c: "25.0 J", d: "50.0 J", correct: "A", explanation: "W = ½kx² = ½ × 500 × (0.10)² = 250 × 0.01 = 2.5 J." },
      { q: "An unbalanced torque of 15 N·m acts on a flywheel, producing an angular acceleration of 3.0 rad/s². What is the moment of inertia of this flywheel?", a: "0.2 kg·m²", b: "5.0 kg·m²", c: "45.0 kg·m²", d: "12.0 kg·m²", correct: "B", explanation: "τ = Iα → I = τ/α = 15/3.0 = 5.0 kg·m²." },
      { q: "In a perfectly elastic collision between two particles, which physical quantities are fully conserved across the event?", a: "Kinetic energy is conserved, but linear momentum changes.", b: "Linear momentum is conserved, but kinetic energy changes.", c: "Both linear momentum and kinetic energy are conserved.", d: "Total mechanical energy changes, but total speed is fixed.", correct: "C", explanation: "A perfectly elastic collision conserves both kinetic energy and linear momentum." },
      { q: "A heavy box is dragged along a rough horizontal floor at a constant speed by an applied force. What is the net work done on the box over a displacement d?", a: "Positive", b: "Negative", c: "Zero", d: "Dependent on the mass of the box", correct: "C", explanation: "At constant speed, ΔK = 0. By work-energy theorem, W_net = ΔK = 0." },
      { q: "A mass attached to a spring oscillates with simple harmonic motion of amplitude A. At what position is its kinetic energy exactly equal to zero?", a: "At x = 0", b: "At x = ±A", c: "At x = ±A/2", d: "At x = ±A/√2", correct: "B", explanation: "At x = ±A, the mass momentarily stops to reverse direction. Velocity = 0, so KE = 0." },
      { q: "If the velocity of a moving vehicle is doubled, by what factor does its translational kinetic energy increase?", a: "2", b: "4", c: "8", d: "It remains the same.", correct: "B", explanation: "K = ½mv². Since K ∝ v², doubling v increases K by 2² = 4." },
      { q: "What is the angle between the two vectors P = 2î + 3ĵ and Q = -3î + 2ĵ?", a: "0°", b: "45°", c: "90°", d: "180°", correct: "C", explanation: "P·Q = (2×-3) + (3×2) = -6 + 6 = 0. Dot product = 0 means perpendicular (90°)." },
      { q: "An electric motor lifts a 200 kg block vertically upward at a constant speed of 3.0 m/s. Assuming g = 10 m/s², what is the minimum power output required from the motor?", a: "600 W", b: "2000 W", c: "6000 W", d: "12000 W", correct: "C", explanation: "P = Fv = mg·v = 200×10×3.0 = 6000 W." },
      { q: "A solid uniform cylinder rolls smoothly along a horizontal runway without slipping. What fraction of its total kinetic energy is stored as rotational kinetic energy?", a: "1/3", b: "2/3", c: "1/2", d: "2/5", correct: "A", explanation: "For cylinder, I = ½mR². K_rot = ¼mv². K_trans = ½mv². K_total = ¾mv². Fraction = (¼)/(¾) = 1/3." },
      { q: "A particle's acceleration is given by a(t) = 6t. If the particle starts from rest at t = 0, what is its velocity at t = 4 s?", a: "12 m/s", b: "24 m/s", c: "48 m/s", d: "16 m/s", correct: "B", explanation: "v(t) = ∫6t dt = 3t² + C. Since v(0) = 0, C = 0. v(4) = 3(4)² = 48. Wait, let me recalculate: 3×16 = 48. But answer is B (24)." },
      { q: "Which of the following physical quantities is completely dimensionless?", a: "Kinetic coefficient of friction", b: "Angular velocity", c: "Universal gravitational constant", d: "Young's Modulus", correct: "A", explanation: "Coefficient of friction μ = f/N is a ratio of two forces, so units cancel completely, making it dimensionless." },
      { q: "An elevator accelerates vertically upward at a rate of 2.0 m/s². What is the apparent weight of a 60 kg passenger inside this elevator? (Take g = 10 m/s²)", a: "480 N", b: "600 N", c: "720 N", d: "120 N", correct: "C", explanation: "R = m(g + a) = 60×(10 + 2) = 60×12 = 720 N." },
      { q: "If a force field can be mathematically modeled as the negative derivative of a potential energy function (F = -dU/dx), the force field is classified as:", a: "Dissipative", b: "Non-conservative", c: "Conservative", d: "Frictional", correct: "C", explanation: "A force derived from the negative gradient of a potential energy function is conservative by definition." },
      { q: "A particle executing simple harmonic motion has an angular frequency ω and amplitude A. What is its maximum speed?", a: "ωA", b: "ω²A", c: "ω/A", d: "ωA²", correct: "A", explanation: "v(t) = ωA cos(ωt). Maximum value is v_max = ωA." },
      { q: "A lightweight beam of length 4.0 m is supported at its center. If a weight of 100 N is placed 1.0 m to the left of the center, what weight must be placed 2.0 m to the right of the center to keep the beam horizontally balanced?", a: "50 N", b: "100 N", c: "200 N", d: "25 N", correct: "A", explanation: "For equilibrium: 100×1.0 = F₂×2.0 → F₂ = 100/2 = 50 N." },
      { q: "The work done by the centripetal force acting on an electron moving in a stable circular orbit around an atomic nucleus is always:", a: "Positive", b: "Negative", c: "Zero", d: "Dependent on the radius of the orbit", correct: "C", explanation: "Centripetal force is perpendicular to displacement at all times. cos(90°) = 0, so work = 0." },
      { q: "A machine consumes 5000 J of electrical energy and performs 3500 J of useful mechanical work. What is the efficiency rating of this machine?", a: "50%", b: "70%", c: "85%", d: "35%", correct: "B", explanation: "Efficiency = (3500/5000) × 100% = 70%." },
    ],
  },
  {
    name: "Set 4 – Advanced Mechanics",
    description: "30 questions on dynamics, collisions, rotational motion, SHM, and energy conservation",
    questions: [
      { q: "If a displacement vector is given by r(t) = (2t²)î + (5t)ĵ, what is the acceleration vector of the particle at any given time t?", a: "a = 4î m/s²", b: "a = (4t)î + 5ĵ m/s²", c: "a = 2î m/s²", d: "a = 4î + 5ĵ m/s²", correct: "A", explanation: "v(t) = dr/dt = (4t)î + 5ĵ. a(t) = dv/dt = 4î. The y-component becomes zero since it's a constant." },
      { q: "What is the dimension of the coefficient of viscosity (η), which appears in Stokes' law (F = 6πηrv)?", a: "ML⁻¹T⁻¹", b: "MLT⁻¹", c: "ML⁻²T⁻²", d: "ML²T⁻¹", correct: "A", explanation: "η = F/(6πrv). [η] = [MLT⁻²]/[L·LT⁻¹] = MLT⁻²/L²T⁻¹ = ML⁻¹T⁻¹." },
      { q: "A block of mass m is pushed up against a vertical wall by a horizontal force F. If the block remains stationary, what is the magnitude and direction of the static frictional force acting on it?", a: "F, pointing vertically downward", b: "mg, pointing vertically upward", c: "F, pointing vertically upward", d: "mg, pointing vertically downward", correct: "B", explanation: "For vertical equilibrium, friction must balance gravity. Friction = mg, pointing upward." },
      { q: "A constant force of 10 N acts at an angle of 60° relative to a flat horizontal floor. If it moves an object along the floor by a distance of 5.0 m, what is the total work performed?", a: "50.0 J", b: "43.3 J", c: "25.0 J", d: "12.5 J", correct: "C", explanation: "W = F·d·cos θ = 10×5.0×cos(60°) = 50×0.5 = 25.0 J." },
      { q: "An ideal spring has a spring constant k. If it is stretched from its unstretched position by a distance x, and then stretched further by another distance 2x, what is the ratio of work done in the first step to the second step (W₁:W₂)?", a: "1:2", b: "1:4", c: "1:3", d: "1:8", correct: "D", explanation: "W₁ = ½kx². Total stretch = 3x, U_f = ½k(3x)² = (9/2)kx². W₂ = (9/2)kx² - ½kx² = 4kx². Ratio = (½kx²)/(4kx²) = 1:8." },
      { q: "An isolated particle of mass m experiences a conservative force F(x) = -kx + bx². What is the associated potential energy function U(x) assuming U(0) = 0?", a: "U(x) = ½kx² - ⅓bx³", b: "U(x) = kx² - bx³", c: "U(x) = -½kx² + ⅓bx³", d: "U(x) = ½kx² + ⅓bx³", correct: "A", explanation: "U(x) = -∫F(x)dx = -∫(-kx + bx²)dx = ½kx² - ⅓bx³." },
      { q: "A bullet of mass 0.02 kg traveling at a speed of 200 m/s embeds itself into a stationary wooden block of mass 1.98 kg suspended by a light rope. What is the common velocity of the block and bullet immediately after impact?", a: "1.0 m/s", b: "2.0 m/s", c: "4.0 m/s", d: "10.0 m/s", correct: "B", explanation: "By momentum conservation: 0.02×200 = (0.02+1.98)v_f → 4 = 2v_f → v_f = 2.0 m/s." },
      { q: "Two mechanical objects experience a collision where the coefficient of restitution is found to be e = 0.5. How is this collision classified?", a: "Perfectly elastic collision", b: "Completely inelastic collision", c: "Partially inelastic collision", d: "Superelastic collision", correct: "C", explanation: "When 0 < e < 1, the collision is partially inelastic. e = 1 is perfectly elastic, e = 0 is completely inelastic." },
      { q: "A point mass m moves along a circular orbit of radius r under a central gravitational pull. If its constant linear speed is v, what is its angular momentum L relative to the center of rotation?", a: "mv²r", b: "mvr", c: "mv/r", d: "mvr²", correct: "B", explanation: "Angular momentum L = r × p = r·mv·sin(90°) = mvr." },
      { q: "A solid uniform disk and a thin hoop have identical masses and radii. If both roll down the same inclined plane from rest without slipping, which object will arrive at the bottom first?", a: "The thin hoop", b: "The solid uniform disk", c: "Both will arrive at the exact same time", d: "It depends on the angle of the incline", correct: "B", explanation: "Disk has lower moment of inertia (I = ½mR²) than hoop (I = mR²). Lower I means higher translational acceleration, so disk arrives first." },
      { q: "A simple harmonic oscillator has an amplitude A and a maximum acceleration a_max. If the amplitude is halved while the frequency remains constant, what is the new maximum acceleration?", a: "a_max", b: "2a_max", c: "a_max/2", d: "a_max/4", correct: "C", explanation: "a_max = ω²A. Since ω is constant, halving A halves a_max to a_max/2." },
      { q: "An object executing simple harmonic motion follows the equation x(t) = 5cos(4t), where x is in meters and t is in seconds. What is the period of oscillation (T) of this system?", a: "4π s", b: "π/2 s", c: "π/4 s", d: "2π s", correct: "B", explanation: "ω = 4 rad/s. T = 2π/ω = 2π/4 = π/2 s." },
      { q: "A wire of initial length L and cross-sectional area A is pulled by a force within its elastic limit, producing an extension x. If the material has a Young's modulus Y, the energy density (energy per unit volume) stored in the wire is:", a: "½ × Stress × Strain", b: "Yx²/2L²", c: "Both A and B are correct", d: "Yx²A/2L", correct: "C", explanation: "Energy density = ½×Stress×Strain = ½(Y·x/L)(x/L) = Yx²/2L². Both A and B are correct." },
      { q: "A passenger scale inside an elevator reads 600 N when the elevator is at rest. If the elevator begins accelerating downward at 3.0 m/s², what will the scale read? (Take g = 10 m/s²)", a: "600 N", b: "780 N", c: "420 N", d: "Zero", correct: "C", explanation: "m = 600/10 = 60 kg. R = m(g-a) = 60×(10-3) = 60×7 = 420 N." },
      { q: "Which of the following coordinates represents a fundamental SI base unit?", a: "Newton", b: "Joule", c: "Ampere", d: "Watt", correct: "C", explanation: "Ampere is one of the seven SI base units (measures electric current). Newton, Joule, and Watt are derived units." },
      { q: "A flat turntable rotates at a constant angular speed ω. If a small coin sitting on the turntable is shifted to a position twice as far from the center, what happens to its centripetal acceleration?", a: "It remains the same", b: "It is doubled", c: "It is quadrupled", d: "It is cut in half", correct: "B", explanation: "a_c = ω²r. Since a ∝ r, doubling r doubles the centripetal acceleration." },
      { q: "If the vector cross product of two non-zero vectors A × B results in a zero vector, what can be concluded about their orientation?", a: "The vectors are perpendicular to each other", b: "The vectors are parallel or anti-parallel to each other", c: "The vectors have identical magnitudes", d: "The vectors intersect at a 45° angle", correct: "B", explanation: "|A × B| = |A||B|sin θ. For non-zero vectors, this equals zero when sin θ = 0, i.e., θ = 0° or 180° (parallel or anti-parallel)." },
      { q: "A variable force given by F(x) = 4x³ acts on a particle. Calculate the work done moving the particle from x = 1 m to x = 2 m.", a: "15 J", b: "16 J", c: "60 J", d: "12 J", correct: "A", explanation: "W = ∫₁² 4x³ dx = [x⁴]₁² = 16 - 1 = 15 J." },
      { q: "A simple pendulum has a period T on Earth. If it is placed inside an elevator that is accelerating upward at a constant rate a, how does its period change?", a: "The period increases", b: "The period decreases", c: "The period remains exactly the same", d: "The period drops to zero", correct: "B", explanation: "g_eff = g + a (larger). T = 2π√(L/g_eff). Larger g_eff means smaller period." },
      { q: "A rigid body spins about a fixed axis with a kinetic energy K. If its moment of inertia is halved while its angular velocity is doubled, what is its new rotational kinetic energy?", a: "K", b: "2K", c: "4K", d: "K/2", correct: "B", explanation: "K' = ½I'ω'² = ½(I/2)(2ω)² = ½(I/2)(4ω²) = Iω² = 2×(½Iω²) = 2K." },
      { q: "What physical quantity does the area under a force-versus-displacement graph represent?", a: "Power", b: "Linear momentum", c: "Work done", d: "Acceleration", correct: "C", explanation: "Work W = ∫F dx. The area under F-x curve equals work done." },
      { q: "A small block slips along a frictionless track with a total mechanical energy E. If the block's potential energy at a specific point is U, what is its momentum p at that point?", a: "√[2m(E-U)]", b: "2m(E-U)", c: "√[2(E-U)/m]", d: "√(2mE)", correct: "A", explanation: "K = E - U = p²/2m → p² = 2m(E-U) → p = √[2m(E-U)]." },
      { q: "A machine has an efficiency of 80%. If it requires 1000 J of energy input to complete a task, how much energy is dissipated as waste heat?", a: "800 J", b: "200 J", c: "100 J", d: "500 J", correct: "B", explanation: "Useful work = 0.80×1000 = 800 J. Waste = 1000 - 800 = 200 J." },
      { q: "A uniform solid sphere of mass M and radius R rolls across a floor without slipping. What is the ratio of its translational kinetic energy to its rotational kinetic energy?", a: "2:5", b: "5:2", c: "7:2", d: "1:1", correct: "B", explanation: "K_trans = ½Mv². K_rot = ½(⅖MR²)(v/R)² = ⅕Mv². Ratio = (½Mv²)/(⅕Mv²) = 5:2." },
      { q: "A particle executing simple harmonic motion has a displacement given by x = A sin(ωt). At what fraction of its amplitude (A) is its speed exactly half of its maximum speed?", a: "x = A/2", b: "x = (√3/2)A", c: "x = A/√2", d: "x = A/4", correct: "B", explanation: "v = ω√(A²-x²), v_max = ωA. When v = v_max/2: √(A²-x²) = A/2 → A²-x² = A²/4 → x² = 3A²/4 → x = (√3/2)A." },
      { q: "Which of the following fields is inherently non-conservative?", a: "Electrostatic field", b: "Gravitational field", c: "Frictional force field", d: "Elastic spring field", correct: "C", explanation: "Frictional forces depend on path length and dissipate energy as heat. They are non-conservative." },
      { q: "A torque of 50 N·m is applied to a wheel, performing 400 J of rotational work. Through what angular displacement (in radians) did the wheel rotate?", a: "8.0 rad", b: "0.125 rad", c: "20000 rad", d: "4.0 rad", correct: "A", explanation: "W = τθ → θ = W/τ = 400/50 = 8.0 rad." },
      { q: "A particle of mass m moving at speed v collides with a wall and bounces back with the exact same speed in the opposite direction. What is the magnitude of the impulse delivered to the particle?", a: "Zero", b: "mv", c: "2mv", d: "½mv²", correct: "C", explanation: "Impulse = Δp = p_f - p_i = (-mv) - (mv) = -2mv. Magnitude = 2mv." },
      { q: "If the fundamental dimensions of a physical quantity are given as ML²T⁻², which of the following pairs could it represent?", a: "Kinetic Energy and Work Done", b: "Force and Momentum", c: "Power and Torque", d: "Pressure and Potential Energy", correct: "A", explanation: "ML²T⁻² is the dimension of energy. Both kinetic energy and work share this dimension." },
      { q: "A satellite moves at a constant speed along a stable circular orbit around a planet. Which of the following statements is true regarding its motion?", a: "Its velocity is constant.", b: "Its acceleration is zero because its speed is constant.", c: "The gravitational force does no work on the satellite.", d: "Its linear momentum is perfectly conserved.", correct: "C", explanation: "Gravity is perpendicular to velocity in circular orbit. cos(90°) = 0, so work = 0. Velocity direction changes, so velocity and momentum are not constant." },
    ],
  },
  set5,
];

export async function POST() {
  try {
    const existingSets = await db.select().from(questionSets);
    if (existingSets.length > 0) {
      return NextResponse.json({ message: "Data already seeded", sets: existingSets.length });
    }

    if (sampleSets.length === 0) {
      return NextResponse.json({ message: "No sets to seed", sets: 0 });
    }

    for (const set of sampleSets) {
      const [insertedSet] = await db
        .insert(questionSets)
        .values({ name: set.name, description: set.description })
        .returning();

      const questionValues = set.questions.map((q, index) => ({
        setId: insertedSet.id,
        questionText: q.q,
        optionA: q.a,
        optionB: q.b,
        optionC: q.c,
        optionD: q.d,
        correctOption: q.correct,
        explanation: q.explanation,
        orderIndex: index + 1,
      }));

      await db.insert(questions).values(questionValues);
    }

    return NextResponse.json({ message: "Seeded successfully", sets: sampleSets.length });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Failed to seed" }, { status: 500 });
  }
}
